### ISSUE TITLE
Square crop

### ISSUE THREAD

**Issue by mahramane** [rroohit/ImageCropView#1]
Hi 
Thank you for build this library
how can i crop image as square?

**Comment by rroohit** [comment]
Thank you for raising this concern.
Currently the library supports only free style cropping.
 
Currently the cropped bitmap image is by default resized to given size to Modifier. The square Crop you can achieve by giving the square size to modifier so the cropped image will be resized to given square size only.

I've taken note of your request, and I'll prioritize implementing square cropping feature in the upcoming releases.

**Comment by rroohit** [comment]
Added Square crop feature in version - 2.2.0
