### ISSUE TITLE
.onCrop returns the first loaded image instead of the new one after reloading ImageCrop

### ISSUE THREAD

**Issue by jsalgueroibarrola** [rroohit/ImageCropView#3]
👋 Hello,

I’ve encountered an issue. When selecting an image and then another one, and reloading the ImageCrop, everything works fine. However, when using .onCrop, it returns the first image that was loaded and not the new one, even though visually the ImageCropView displays it correctly.

**Comment by rroohit** [comment]
Hi,
Thank you for reaching out and reporting the issue.
Could you please let us know which version of the ImageCrop library you are using? This information will help us identify the issue more precisely.

**Comment by jsalgueroibarrola** [comment]
I am using version 3.0.0 of the ImageCrop library.

**Comment by rroohit** [comment]
Thanks,

We've identified the cause of the problem.
We expect to have the fix ready in the next few days, so please keep an eye on the latest release for updates.
